### ISSUE TITLE
Python3-gi-cairo package is missing

### ISSUE THREAD

**Issue by JasperJuergensen** [linuxmint/mintsources#190]
Hi,
after upgrading to Linux Mint 19.3 Tricia mintsources (Version: 1.9.1; Python 3.6.9) fails with the following error:
```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1918, in <module>
    Application().run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 968, in __init__
    self.detect_official_sources()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1833, in detect_official_sources
    self.update_flags()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1876, in update_flags
    surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, self.scale)
TypeError: Couldn't find foreign struct converter for 'cairo.Surface'
```

Solved the problem with installing the `python3-gi-cairo` package. Maybe the package should be added to the debian package dependencies.

**Comment by xenopeek** [comment]
Confirming that mintsources requires python3-gi-cairo; with it not installed it gives the error you posted. I've done a PR to add it to the package: https://github.com/linuxmint/mintsources/pull/194
