### ISSUE TITLE
mintsources crash

### ISSUE THREAD

**Issue by msalini** [linuxmint/mintsources#204]
I am on LinuxMint 19.3 Xfce (upgraded from Mint 19 Xfce).

`uname -a`
`Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

After making a package source refresh via update manager, I got a "repo not found" for one of the repositories. I tried to remove the repo via Synaptic, but the window wouldn't open. Hence I removed the file manually in /etc/apt/sources.list.d/ and updated again, successfully. However, the "Software Sources" in Update Manager and "Repositories" in Synaptic still wouldn't open.

I get this error when I issue the command `sudo mintsources` :

> Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 11, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
ModuleNotFoundError: No module named 'six'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintSources_mintSources.py.0.crash'

> Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 11, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
ModuleNotFoundError: No module named 'six'

I do have python-six installed:
`dpkg -l | grep python-six`
`ii  python-six                                  1.11.0-2 `

Any idea?

**Comment by xenopeek** [comment]
For help with your issue please ask on the support forums: https://forums.linuxmint.com/viewforum.php?f=47. If it turns out the cause of your issue is a bug in mintsources, you can reopen this here. See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).

**Comment by msalini** [comment]
I posted the issue in the forum:
https://forums.linuxmint.com/viewtopic.php?f=47&t=320453&p=1818372&sid=34d9a72800226ea91ccee597c19dd8db

Unfortunately I got no response and the error still persists.
I did search online but I got no solutions that I could easily apply to my case.

I was wondering if you can help getting through this.
Thanks

**Comment by crigoda** [comment]
I'm not an Ubuntu user but on Debian, Python packages are available for Python 2 and Python 3.
Python-six may be the Python 2.7 version. Check if you have python3-six installed.
