### ISSUE TITLE
Mintsources 2.3.0 is not working

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintsources#250]
Hi,

Mintsources 2.3.0 is not working on my testbed LM 22 (installed from Ubuntu minimal and added LM repos).

`mintsources 
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1896, in <module>
    Application(os_codename).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 893, in __init__
    self.read_source_lists()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1024, in read_source_lists
    source = Source(self, repo)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 408, in __init__
    self.ppa_owner, self.ppa_name = self.name.split("/")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)`

**Comment by kelebek333** [comment]
I fixed it myself
