### ISSUE TITLE
mintsources crashes silently without software-sources.svg

### ISSUE THREAD

**Issue by aesdana** [linuxmint/mintsources#73]
mintsources fails to start from mintupdate with no messages or notifications if there is no `/usr/share/icons/hicolor/scalable/apps/software-sources.svg` file

From terminal I got this:
```python
    Application().run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 608, in __init__
    self._main_window.set_icon_from_file("/usr/share/icons/hicolor/scalable/apps/software-sources.svg")
glib.GError: Failed to open file "/usr/share/icons/hicolor/scalable/apps/software-sources.svg": No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 138, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
OSError: [Errno 2] No such file or directory: "/var/crash/_usr_lib_linuxmint_mintSources_mintSources.py.0.crash"
Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1459, in <module>
    Application().run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 608, in __init__
    self._main_window.set_icon_from_file("/usr/share/icons/hicolor/scalable/apps/software-sources.svg")
glib.GError: Failed to open file "/usr/share/icons/hicolor/scalable/apps/software-sources.svg": No such file or directory
```

I lost /usr/share/icons/hicolor/ directory and had to reinstall minsources to get /usr/share/icons/hicolor/scalable/apps/software-sources.svg again but don't you think it's odd no to start application with missing icon? Okay, it's a a part of interface but why not to drop some notification like "Hey, reinstall me I'm broken!"?

```
Distributor ID: LinuxMint
Description:    Linux Mint 17.3 Rosa
Release:        17.3
Codename:       rosa
```

```
pkg -l | grep mintsources
ii  mintsources                                 1.5.2                                                  all          Software Sources configuration tool
```

**Comment by JosephMcc** [comment]
This should no longer happen after https://github.com/linuxmint/mintsources/commit/3626b2a9d48fc67bbc7d2e9cb9e9302bcfc6509c
